create table if not exists public.lamy_pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  status text not null default 'draft' check (status in ('draft', 'published')),
  project_data jsonb,
  html text not null default '',
  css text not null default '',
  js text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists lamy_pages_status_updated_at_idx
  on public.lamy_pages (status, updated_at desc);

alter table public.lamy_pages enable row level security;

grant usage on schema public to service_role;
revoke all on table public.lamy_pages from anon, authenticated;
grant select, insert, update, delete on table public.lamy_pages to service_role;
grant usage, select on sequence public.lamy_pages_id_seq to service_role;
