alter table public.lamy_pages
  add column if not exists path text,
  add column if not exists source_file text,
  add column if not exists latest_draft_version_id bigint,
  add column if not exists published_version_id bigint,
  add column if not exists previous_published_version_id bigint;

alter table public.lamy_pages
  drop constraint if exists lamy_pages_path_format_check;

alter table public.lamy_pages
  add constraint lamy_pages_path_format_check
  check (
    path is null
    or (
      left(path, 1) = '/'
      and position('?' in path) = 0
      and position('#' in path) = 0
      and position(E'\\' in path) = 0
    )
  );

create unique index if not exists lamy_pages_path_unique_idx
  on public.lamy_pages (path)
  where path is not null;

create table if not exists public.lamy_page_versions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.lamy_pages(id) on delete cascade,
  version_number bigint not null check (version_number > 0),
  title text not null,
  slug text not null,
  project_data jsonb,
  html text not null default '',
  css text not null default '',
  js text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (page_id, version_number)
);

create index if not exists lamy_page_versions_page_version_idx
  on public.lamy_page_versions (page_id, version_number desc);

insert into public.lamy_page_versions (
  page_id,
  version_number,
  title,
  slug,
  project_data,
  html,
  css,
  js,
  created_at,
  updated_at
)
select
  page.id,
  1,
  page.title,
  page.slug,
  page.project_data,
  page.html,
  page.css,
  page.js,
  page.created_at,
  page.updated_at
from public.lamy_pages page
where not exists (
  select 1
  from public.lamy_page_versions version
  where version.page_id = page.id
);

update public.lamy_pages page
set
  latest_draft_version_id = version.id,
  published_version_id = case
    when page.status = 'published' then version.id
    else null
  end
from public.lamy_page_versions version
where version.page_id = page.id
  and version.version_number = 1
  and page.latest_draft_version_id is null;

alter table public.lamy_pages
  drop constraint if exists lamy_pages_latest_draft_version_fk,
  drop constraint if exists lamy_pages_published_version_fk,
  drop constraint if exists lamy_pages_previous_published_version_fk;

alter table public.lamy_pages
  add constraint lamy_pages_latest_draft_version_fk
    foreign key (latest_draft_version_id)
    references public.lamy_page_versions(id)
    deferrable initially deferred,
  add constraint lamy_pages_published_version_fk
    foreign key (published_version_id)
    references public.lamy_page_versions(id)
    deferrable initially deferred,
  add constraint lamy_pages_previous_published_version_fk
    foreign key (previous_published_version_id)
    references public.lamy_page_versions(id)
    deferrable initially deferred;

create or replace view public.lamy_page_drafts
with (security_invoker = true)
as
select
  page.id,
  page.path,
  page.source_file,
  page.status,
  page.created_at,
  page.updated_at,
  page.published_at,
  page.latest_draft_version_id,
  page.published_version_id,
  page.previous_published_version_id,
  version.id as version_id,
  version.version_number,
  version.title,
  version.slug,
  version.project_data,
  version.html,
  version.css,
  version.js,
  (
    page.published_version_id is null
    or page.latest_draft_version_id is distinct from page.published_version_id
  ) as has_unpublished_changes
from public.lamy_pages page
join public.lamy_page_versions version
  on version.id = page.latest_draft_version_id
 and version.page_id = page.id;

create or replace view public.lamy_page_published
with (security_invoker = true)
as
select
  page.id,
  page.path,
  page.source_file,
  page.status,
  page.created_at,
  page.updated_at,
  page.published_at,
  page.latest_draft_version_id,
  page.published_version_id,
  page.previous_published_version_id,
  version.id as version_id,
  version.version_number,
  version.title,
  version.slug,
  version.project_data,
  version.html,
  version.css,
  version.js,
  (
    page.latest_draft_version_id is distinct from page.published_version_id
  ) as has_unpublished_changes
from public.lamy_pages page
join public.lamy_page_versions version
  on version.id = page.published_version_id
 and version.page_id = page.id
where page.status = 'published';

create or replace function public.cms_create_page(
  p_title text,
  p_slug text,
  p_path text default null,
  p_source_file text default null,
  p_timestamp timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_page_id bigint;
  v_version_id bigint;
begin
  insert into public.lamy_pages (
    title,
    slug,
    path,
    source_file,
    status,
    project_data,
    html,
    css,
    js,
    created_at,
    updated_at
  )
  values (
    p_title,
    p_slug,
    p_path,
    p_source_file,
    'draft',
    null,
    '',
    '',
    '',
    p_timestamp,
    p_timestamp
  )
  returning id into v_page_id;

  insert into public.lamy_page_versions (
    page_id,
    version_number,
    title,
    slug,
    project_data,
    html,
    css,
    js,
    created_at,
    updated_at
  )
  values (
    v_page_id,
    1,
    p_title,
    p_slug,
    null,
    '',
    '',
    '',
    p_timestamp,
    p_timestamp
  )
  returning id into v_version_id;

  update public.lamy_pages
  set latest_draft_version_id = v_version_id
  where id = v_page_id;

  return v_page_id;
end;
$$;

create or replace function public.cms_save_page_draft(
  p_page_id bigint,
  p_title text,
  p_slug text,
  p_project_data jsonb,
  p_html text,
  p_css text,
  p_js text,
  p_timestamp timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_page public.lamy_pages%rowtype;
  v_version_number bigint;
  v_version_id bigint;
begin
  select *
  into v_page
  from public.lamy_pages
  where id = p_page_id
  for update;

  if not found then
    raise exception 'Página % não encontrada.', p_page_id
      using errcode = 'P0002';
  end if;

  select coalesce(max(version_number), 0) + 1
  into v_version_number
  from public.lamy_page_versions
  where page_id = p_page_id;

  insert into public.lamy_page_versions (
    page_id,
    version_number,
    title,
    slug,
    project_data,
    html,
    css,
    js,
    created_at,
    updated_at
  )
  values (
    p_page_id,
    v_version_number,
    p_title,
    p_slug,
    p_project_data,
    coalesce(p_html, ''),
    coalesce(p_css, ''),
    coalesce(p_js, ''),
    p_timestamp,
    p_timestamp
  )
  returning id into v_version_id;

  update public.lamy_pages
  set
    title = p_title,
    slug = p_slug,
    project_data = p_project_data,
    html = coalesce(p_html, ''),
    css = coalesce(p_css, ''),
    js = coalesce(p_js, ''),
    latest_draft_version_id = v_version_id,
    updated_at = p_timestamp
  where id = p_page_id;

  return v_version_id;
end;
$$;

create or replace function public.cms_publish_page(
  p_page_id bigint,
  p_version_id bigint,
  p_timestamp timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_page public.lamy_pages%rowtype;
  v_slug text;
begin
  select *
  into v_page
  from public.lamy_pages
  where id = p_page_id
  for update;

  if not found then
    raise exception 'Página % não encontrada.', p_page_id
      using errcode = 'P0002';
  end if;

  if v_page.latest_draft_version_id is null then
    raise exception 'Página % não possui rascunho salvo.', p_page_id
      using errcode = 'P0001';
  end if;

  if v_page.latest_draft_version_id is distinct from p_version_id then
    raise exception 'O rascunho da página % mudou durante a publicação.', p_page_id
      using errcode = '40001';
  end if;

  select version.slug
  into v_slug
  from public.lamy_page_versions version
  where version.id = p_version_id
    and version.page_id = p_page_id;

  if not found then
    raise exception 'Rascunho da página % é inválido.', p_page_id
      using errcode = '23503';
  end if;

  if exists (
    select 1
    from public.lamy_pages other_page
    join public.lamy_page_versions published_version
      on published_version.id = other_page.published_version_id
     and published_version.page_id = other_page.id
    where other_page.id <> p_page_id
      and published_version.slug = v_slug
  ) then
    raise exception 'O slug publicado "%" já pertence a outra página.', v_slug
      using errcode = '23505';
  end if;

  update public.lamy_pages
  set
    previous_published_version_id = published_version_id,
    published_version_id = p_version_id,
    status = 'published',
    published_at = p_timestamp
  where id = p_page_id;

  return p_version_id;
end;
$$;

create or replace function public.cms_rollback_page(
  p_page_id bigint,
  p_version_id bigint default null,
  p_timestamp timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_page public.lamy_pages%rowtype;
  v_target_version_id bigint;
begin
  select *
  into v_page
  from public.lamy_pages
  where id = p_page_id
  for update;

  if not found then
    raise exception 'Página % não encontrada.', p_page_id
      using errcode = 'P0002';
  end if;

  v_target_version_id := coalesce(p_version_id, v_page.previous_published_version_id);

  if v_target_version_id is null then
    raise exception 'Página % não possui versão publicada anterior.', p_page_id
      using errcode = 'P0001';
  end if;

  if not exists (
    select 1
    from public.lamy_page_versions version
    where version.id = v_target_version_id
      and version.page_id = p_page_id
  ) then
    raise exception 'Versão % não pertence à página %.', v_target_version_id, p_page_id
      using errcode = '23503';
  end if;

  update public.lamy_pages
  set
    previous_published_version_id = published_version_id,
    published_version_id = v_target_version_id,
    status = 'published',
    published_at = p_timestamp
  where id = p_page_id;

  return v_target_version_id;
end;
$$;

alter table public.lamy_page_versions enable row level security;

revoke all on table public.lamy_page_versions from anon, authenticated;
revoke all on table public.lamy_page_versions from service_role;
grant select on table public.lamy_page_versions to service_role;

revoke all on table public.lamy_page_drafts from anon, authenticated;
revoke all on table public.lamy_page_published from anon, authenticated;
grant select on table public.lamy_page_drafts to service_role;
grant select on table public.lamy_page_published to service_role;

revoke insert, update, delete on table public.lamy_pages from service_role;
grant select on table public.lamy_pages to service_role;

revoke all on function public.cms_create_page(text, text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.cms_save_page_draft(bigint, text, text, jsonb, text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.cms_publish_page(bigint, bigint, timestamptz) from public, anon, authenticated;
revoke all on function public.cms_rollback_page(bigint, bigint, timestamptz) from public, anon, authenticated;

grant execute on function public.cms_create_page(text, text, text, text, timestamptz) to service_role;
grant execute on function public.cms_save_page_draft(bigint, text, text, jsonb, text, text, text, timestamptz) to service_role;
grant execute on function public.cms_publish_page(bigint, bigint, timestamptz) to service_role;
grant execute on function public.cms_rollback_page(bigint, bigint, timestamptz) to service_role;
